Vagrant.configure("2") do |config|

  ("a".."b").each do |id|
    config.vm.define "vm#{id}" do |machine|
      machine.vm.box = "alvistack/ubuntu-24.04"
      machine.vm.network "private_network", ip: "192.168.56.1#{id == 'a' ? '0' : '1'}"
      machine.vm.hostname = "vm#{id}"
      machine.vm.synced_folder "..", "/home/vagrant/tp1"

      machine.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.name = "vm#{id}"
      end
    
      machine.vm.provision "shell", inline: <<-SHELL
        # Get updated urls/packages sources & tools
        apt-get update
        # Get several software packages including gcc and java
        apt-get install -y net-tools joe zip build-essential default-jdk
        # The alias for ls
        grep -q "alias ls='ls -la'" /home/vagrant/.bashrc || echo -e "\\nalias ls='ls -la'" >> /home/vagrant/.bashrc
      SHELL
    end
  end
end
